server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527
    prefer-ip-address: true

zuul:
  prefix: /wdkang
  ignored-services: "*"
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**

info:
  app.name: wdkang-microcloud
  company.name: www.wdkang.top
  build.artifactId: $project.artifactId$
  build.version: $project.version$
