server:
  port: 8000

spring:
  application:
    name: microservicecloud-dept-feign

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: microservicecloud-dept-feign
    prefer-ip-address: true
